### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Epokhe** [NiklasRosenstein/python-github-bot-api#1]
Hey @NiklasRosenstein,

I would like to use this package at Udemy, but it currently has no license.

If you are okay with the library being used in a commercial setting, would you mind adding a suitable license?

Thank you!

**Comment by NiklasRosenstein** [comment]
Hey @Epokhe , thanks for the heads up. I've added added the MIT license to the project. Would you link the Udemy course here once it's available? 😃 

Cheers,

**Comment by Epokhe** [comment]
@NiklasRosenstein It's not for a Udemy course actually. It's going to be used internally at Udemy infrastructure :)

**Comment by NiklasRosenstein** [comment]
Got you! I hope it serves you well. 👍
