### ISSUE TITLE
Support passing the retry object into the installation_client

### ISSUE THREAD

**Issue by testworksau** [NiklasRosenstein/python-github-bot-api#3]
Thanks for the great work on this library; I've been experimenting with it today.

Since PyGitHub 1.43.6, support for requests -> [urllib3 retry](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry) has been available.

We define our Retry method to retry on a range of different status's, as follows:
```
status_forcelist = (
    HTTPStatus.INTERNAL_SERVER_ERROR,
    HTTPStatus.BAD_GATEWAY,
    HTTPStatus.SERVICE_UNAVAILABLE,
    HTTPStatus.GATEWAY_TIMEOUT
)

retry = Retry(
    total=10,
    connect=10,
    read=10,
    backoff_factor=0.1,
    status_forcelist=status_forcelist
)
```

We pass this through to PyGitHub as follows:

```
github_api = Github(login_or_token=token, retry=retry)
```

It would be great if we could pass this through via the `installation_client`.

**Comment by NiklasRosenstein** [comment]
Closing because of #6 :)
