### ISSUE TITLE
Support configuration of `per_page` in the `installation_client`

### ISSUE THREAD

**Issue by testworksau** [NiklasRosenstein/python-github-bot-api#4]
It would be good if we could initialise the installation client with the `per_page` parameter.

We pass this through to a normal PyGitHub client as follows:

```
github_api = Github(login_or_token=token, per_page=100)
```

It would be great if we could pass this through via the `installation_client` like we can with a regular PyGitHub client, rather than having to set it after the client has been created:

```
github_api.per_page = 100
```

**Comment by NiklasRosenstein** [comment]
Closing because of #6 :)
